repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    # Fix the last lines' trailing whitespace before correcting that they exist.
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
